services:
  mexicanbonora:
    container_name: mexicanbonora
    restart: unless-stopped
    environment:
      TOKEN: ${MEXICANBONORA_TOKEN}
    networks:
      - mexicanbonora

networks:
  mexicanbonora:
