services:
  homeassistant:
    networks:
      lan:
        ipv4_address: 192.168.0.254
        gw_priority: 1

networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          ip_range: "192.168.0.0/24"
          gateway: "192.168.0.1"
